### ISSUE TITLE
A free file hosting site

### ISSUE THREAD

**Issue by BakerBunker** [stet-stet/goct_ismir2023#1]
> If you cannot go through the steps below, I can provide you with the .h5 files. However, I honestly cannot think of a stable way to transport three files that sum up to ~40GB, so you'll have to provide me with a good way to do so.

I found a [free file hosting site](https://qiwi.gg/), maybe you can upload the .h5 file here.

**Comment by stet-stet** [comment]
Thank you, however there seems to be many mentions of this site being a bit suspicious, so I am withholding for now.

**Comment by dudehacker** [comment]
try this?

where ppl host the huge models for AI art
https://huggingface.co/

**Comment by BakerBunker** [comment]
Or host the dataset on [huggingface](https://huggingface.co/docs/datasets/upload_dataset) [kaggle](https://www.kaggle.com/docs/datasets) or cut it to 2gb files and upload through [github release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas)

**Comment by stet-stet** [comment]
Sorry for the late reply.

As you might be able to infer, our dataset contains material copyrighted by many, many parties. While the big file sizes are one reason why I am reluctant to host the files, another would be that I have no idea if redistributing the dataset will go against Korean or American law (both, since I am a dual citizen). And as far as I know, the fair use clause isn't really a thing in Korea, either.

Alternatively, hosting a demo (not the dataset) in Huggingface seems like a very possible thing to do, and I will definitely look into it when I have more time.

Thus, I will be leaving this issue closed. Thank you for your inputs!
